### PR TITLE
Upgraded to python3 and added requirements.txt

### PR DESCRIPTION
**Pull request by notshriram**
[Python 2.7 has reached EOL](https://www.python.org/doc/sunset-python-2/)

Changes added:
- Upgraded source code to Python3
- Added requirements.txt
- Added a couple of sections to README.md pertaining to installation steps.

### CODE REVIEW

**Comment by notshriram** [comment]
Works well on my machine. Please verify on yours.

Using lenna.png (512x512)
```python3 main.py --input lenna.png  --coeffs 1```

image

**Comment by javiribera** [comment]
What python version are you using? I am getting errors when installing the requirements.txt

**Comment by notshriram** [comment]
> What python version are you using? I am getting errors when installing the requirements.txt

I am using python 3.9.12 on macOS 12.4 M1 and pip 22.0.4

**Comment by javiribera** [comment]
It works with Ubuntu 20.04 too. Thank you!

**Pull request merged**
